[package]
name = "nested-mazes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
image = "0.24.2"
rand = "0.8.5"
serde_json = "1.0.81"